### ISSUE TITLE
would you like to add mongodb into your project?

### ISSUE THREAD

**Issue by azl397985856** [sotojuan/saga-login-flow#3]
now the login info is not permanent.  for my sake, it's better to save data on databases.

**Comment by sotojuan** [comment]
Hi Arida, thanks for the interest. This example is very basic and focused on Redux and Redux Saga for async actions, so adding a real database would be unnecessarily complex. I just needed something to "fake" it. You're more than welcome to fork this and make it work with a real server though!

**Comment by azl397985856** [comment]
all right.  thank you anyway
